server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 100MB
      file-size-threshold: 1MB
      location: C:/Temp
      max-request-size: 100MB
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pms?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 'Uni1204@'
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create # create(테스트시), validate(테스트시), none (운영서버)
    properties:
      hibernate:
        format_sql: true

    org:
      hibernate:
        envers:
          audit_table_suffix: _history
          revision_field_name: rev_id
          store_data_at_delete: true

board:
  attach-file:
    storage : C:\\storage\\pms\\board\\attach_file
    url: http://localhost:8081/files/dev/board/attach-file