server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pms?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 'qwer1234!'
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create # create(테스트시), validate(테스트시), none (운영서버)
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: error
    org.hibernate.type.descriptor.sql: trace  #쿼리 인자 데이터 확인
  
 
